# Generated by Django 4.1.7 on 2023-02-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speech', '0002_delete_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
