# Generated by Django 4.1.7 on 2024-07-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfilemodel',
            name='email_address',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
